image: eclipse-temurin:23-jdk-alpine

pipelines:
  default:
    - step:
        name: Run AnyLogic experiment
        script:
          - chmod +x ./DistributionCenter_CustomExperiment/DistributionCenter_linux.sh # Make script executable
          - . /DistributionCenter_CustomExperiment/DistributionCenter_linux.sh # Run the experiment
